./psake.ps1 "default.ps1" "Clean"
./psake.ps1 "default.ps1" "Increment"
./psake.ps1 "default.ps1" "RunBuild" "3.5"
./psake.ps1 "default.ps1" "RunBuild" "4.0"
./psake.ps1 "default.ps1" "BuildInstaller"