using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.4.5.0")]
[assembly: AssemblyFileVersionAttribute("0.4.5.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © NBehave 2007-2009")]
[assembly: AssemblyProductAttribute("NBehave")]
[assembly: AssemblyCompanyAttribute("NBehave")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.4.5.0")]

